-- CreateTable
CREATE TABLE "centro_custo" (
    "ID" SERIAL NOT NULL,
    "DES_CENTRO_CUSTO" VARCHAR(200) NOT NULL,
    "STA_ATIVO" CHAR(1),
    "SIGLA" VARCHAR(100),
    "DATA_INICIAL" DATE,
    "DATA_FINAL" DATE,
    "OBSERVACOES" VARCHAR(2000),

    CONSTRAINT "centro_custo_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "fornecedor" (
    "ID" SERIAL NOT NULL,
    "PESSOA" CHAR(1) NOT NULL,
    "NOM_PESSOA" VARCHAR(100) NOT NULL,
    "DAT_CADASTRO" DATE NOT NULL,
    "NUM_CGC" CHAR(14),
    "NUM_CPF" CHAR(11),
    "EMAIL" VARCHAR(2000) NOT NULL,
    "NOM_CONTATO" VARCHAR(100) NOT NULL,
    "STA_ATIVO" CHAR(1) NOT NULL,
    "NOM_APELIDO" VARCHAR(100),
    "NOM_FANTASIA" VARCHAR(200) NOT NULL,
    "NUM_RG" VARCHAR(15),
    "DES_HISTORICO" VARCHAR(3000),
    "NOM_CARGO" VARCHAR(100),
    "RAMO_ATIVIDADE" VARCHAR(3000),
    "FONE" VARCHAR(100),
    "STA_POSSUI_NFE" CHAR(1),
    "WEBSITE" VARCHAR(200),
    "NUM_INSC_ESTATUAL" VARCHAR(20),
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "fornecedor_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "fornecedor_produto" (
    "ID" SERIAL NOT NULL,
    "ID_FORN" INTEGER NOT NULL,
    "ID_PROD" INTEGER NOT NULL,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "fornecedor_produto_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "movimentacao" (
    "ID" SERIAL NOT NULL,
    "ID_PROD" INTEGER NOT NULL,
    "E_S" CHAR(1) NOT NULL,
    "DATA_MOVTO" DATE NOT NULL,
    "TIPO_MOVTO" INTEGER NOT NULL,
    "QTD" DECIMAL(10,2) NOT NULL,
    "VALOR" DECIMAL(10,2) NOT NULL,
    "VALOR_TOTAL" DECIMAL(10,2) NOT NULL,
    "VALOR_MEDIO" DECIMAL(10,2) NOT NULL,
    "QTD_EST_ATUAL" DECIMAL(10,2) NOT NULL,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "movimentacao_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "produto" (
    "ID" SERIAL NOT NULL,
    "COD_MATERIAL" VARCHAR(30) NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "MARCA" VARCHAR(400) NOT NULL,
    "TIPO_PROD_ID" INTEGER NOT NULL,
    "STA_ATIVO" CHAR(1) NOT NULL,
    "QTD_ESTOQUE_MINIMO" DECIMAL(16,3),
    "QTD_ESTOQUE_MAXIMO" DECIMAL(16,3),
    "UNME_ID" INTEGER NOT NULL,
    "DAT_INCLUSAO" DATE NOT NULL,
    "IMAGEM" BYTEA,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "produto_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "tipo_movimento_estoque" (
    "ID" SERIAL NOT NULL,
    "DES_TIPO_MOVIMENTO" TEXT NOT NULL,
    "DES_OBSERVACAO" TEXT NOT NULL,
    "STA_ATIVO" CHAR(1) NOT NULL,
    "STA_TIPO_MOVIMENTO" CHAR(1) NOT NULL,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "tipo_movimento_estoque_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "tipo_produto" (
    "ID" SERIAL NOT NULL,
    "SEGMENTO" TEXT NOT NULL,
    "STA_CONTROLA_VALIDADE" CHAR(1) NOT NULL,
    "STA_MOV_ESTOQUE" CHAR(1) NOT NULL,
    "UEPS_PEPS" CHAR(1) NOT NULL,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "tipo_produto_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "unidade_medida" (
    "ID" SERIAL NOT NULL,
    "DES_UNIDADE" VARCHAR(40) NOT NULL,
    "UNID_SIGLA" VARCHAR(10) NOT NULL,
    "USER_CAD" INTEGER NOT NULL,
    "DATA_CAD" DATE NOT NULL,

    CONSTRAINT "unidade_medida_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "usuario" (
    "ID" SERIAL NOT NULL,
    "USUARIO" VARCHAR(100) NOT NULL,
    "SENHA" VARCHAR(8) NOT NULL,
    "NOME" VARCHAR(300) NOT NULL,
    "EMAIL" VARCHAR(300),
    "DDD_CELULAR" SMALLINT NOT NULL,
    "CELULAR" INTEGER NOT NULL,

    CONSTRAINT "usuario_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "PRODUTO_UK" ON "produto"("COD_MATERIAL");

-- AddForeignKey
ALTER TABLE "fornecedor" ADD CONSTRAINT "FORNECEDOR_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "fornecedor_produto" ADD CONSTRAINT "FORN_PROD_FORNECEDOR_FK" FOREIGN KEY ("ID_FORN") REFERENCES "fornecedor"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "fornecedor_produto" ADD CONSTRAINT "FORN_PROD_PRODUTO_FK" FOREIGN KEY ("ID_PROD") REFERENCES "produto"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "fornecedor_produto" ADD CONSTRAINT "FORN_PROD_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "movimentacao" ADD CONSTRAINT "MOVTO_FIN_PRODUTO_FK" FOREIGN KEY ("ID_PROD") REFERENCES "produto"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "movimentacao" ADD CONSTRAINT "MOVTO_FIN_TIPO_MOVTO_FK" FOREIGN KEY ("TIPO_MOVTO") REFERENCES "tipo_movimento_estoque"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "movimentacao" ADD CONSTRAINT "MOVTO_FIN_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "produto" ADD CONSTRAINT "PRODUTO_TIPO_PROD_FK" FOREIGN KEY ("TIPO_PROD_ID") REFERENCES "tipo_produto"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "produto" ADD CONSTRAINT "PRODUTO_UNME_FK" FOREIGN KEY ("UNME_ID") REFERENCES "unidade_medida"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "produto" ADD CONSTRAINT "PRODUTO_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tipo_movimento_estoque" ADD CONSTRAINT "TPMOV_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tipo_produto" ADD CONSTRAINT "TIPROD_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "unidade_medida" ADD CONSTRAINT "UNME_USUARIO_FK" FOREIGN KEY ("USER_CAD") REFERENCES "usuario"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
